server:
  port: 8081
  servlet:
    session:
      timeout: 30m
  # 开启 gzip 压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    # 超过 1KB 即开启压缩
    min-response-size: 1024
  # 开启 http2 支持 只在https下起作用
  http2:
    enabled: true



  ###模板配置
  thymeleaf:
    mode: HTML
    cache: false
    encoding: UTF-8


  #redis 配置
  redis:
    host: localhost
    password:
    port: 6379

  # HttpSession redis
  session:
    store-type: redis
    redis:
      flush-mode: ON_SAVE
      namespace: spring



  # 开启浏览器静态资源缓存
  resources:
    cache:
      cachecontrol:
        max-age: 120s
        must-revalidate: true
        cache-public: true
